baseURL = "https://clemens.ms/"
languageCode = "en-us"
title = "Clemens Schotte"

theme = "clemens"

enableEmoji = true
paginate = 5

[author]
  name = "Clemens Schotte"

[params]
   author = "Clemens Schotte"
   description = "Clemens Schotte Blog about technology."

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 3

  [[menu.footer]]
    name = "Privacy policy"
    url = "/privacy-policy/"
    weight = 1
  [[menu.footer]]
    name = "Terms of use"
    url = "/terms-of-use/"
    weight = 2
  [[menu.footer]]
    name = "Contact"
    url = "/contact-clemens-schotte/"
    weight = 3

[taxonomies]
  tag = "tags"

[markup]
  [markup.highlight]
    style = "vs"
