baseURL = "https://clemens.ms/"
languageCode = "en-us"
title = "Clemens Schotte"
copyright = "Copyright by Clemens Schotte"

theme = "clemens"

enableEmoji = true
paginate = 5

googleAnalytics = "UA-43077951-19"
disqusShortname = "clemens-ms"

[author]
  name = "Clemens Schotte"

[params]
   author = "Clemens Schotte"
   description = "Clemens Schotte Blog about technology."

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 2

  [[menu.footer]]
    name = "Privacy policy"
    url = "/privacy-policy/"
    weight = 1
  [[menu.footer]]
    name = "Terms of use"
    url = "/terms-of-use/"
    weight = 2

[markup]
  [markup.highlight]
    style = "vs"
