name: Build and Deploy Hugo site to Azure Blob Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      HUGO_VERSION: 0.148.1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Hugo CLI
      run: |
        wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb && sudo dpkg -i ${{ runner.temp }}/hugo.deb

    - name: Build the website
      run: |
        hugo --minify

    - name: Upload to Azure Blob Storage
      uses: azure/cli@v2
      with:
        inlineScript: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --account-key ${{ secrets.AZURE_STORAGE_KEY }} \
            --destination \$web \
            --source ./public \
            --overwrite
