name: Build and Deploy Hugo site to Azure Blob Storage

on:
  push:
    branches:
      - master  # Changed from main to master to match your repo
  workflow_dispatch:  # Allow manual triggers

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    env:
      HUGO_VERSION: 0.148.1

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch full history for Hugo's .GitInfo

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true

    - name: Cache Hugo modules
      uses: actions/cache@v4
      with:
        path: /tmp/hugo_cache
        key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-hugomod-

    - name: Build the website
      run: |
        hugo --minify --gc --environment production
      env:
        HUGO_CACHEDIR: /tmp/hugo_cache

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: hugo-public
        path: public/
        retention-days: 7

    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload to Azure Blob Storage
      uses: azure/cli@v2
      with:
        inlineScript: |
          # Upload static assets (CSS, JS, images) with long cache
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.css" \
            --content-cache-control "public, max-age=31536000, immutable" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.js" \
            --content-cache-control "public, max-age=31536000, immutable" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.png" \
            --content-cache-control "public, max-age=31536000" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.jpg" \
            --content-cache-control "public, max-age=31536000" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.jpeg" \
            --content-cache-control "public, max-age=31536000" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.svg" \
            --content-cache-control "public, max-age=31536000" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.ico" \
            --content-cache-control "public, max-age=31536000" \
            --verbose
          
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.xml" \
            --content-cache-control "public, max-age=3600" \
            --verbose
          
          # Upload HTML files with short cache for quick content updates
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --pattern "*.html" \
            --content-cache-control "public, max-age=300" \
            --verbose
          
          # Upload any remaining files with medium cache
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --auth-mode login \
            --destination \$web \
            --source ./public \
            --overwrite \
            --exclude-pattern "*.css;*.js;*.png;*.jpg;*.jpeg;*.svg;*.ico;*.html;*.xml" \
            --content-cache-control "public, max-age=3600" \
            --verbose

    - name: Purge Azure CDN
      uses: azure/cli@v2
      with:
        inlineScript: |
          az cdn endpoint purge \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --profile-name ${{ secrets.AZURE_CDN_PROFILE_NAME }} \
            --name ${{ secrets.AZURE_CDN_ENDPOINT_NAME }} \
            --content-paths "/*"

    - name: Deployment status
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Website URL: https://${{ secrets.AZURE_STORAGE_ACCOUNT }}.z6.web.core.windows.net/"
